// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kannan112/mock-trading-platform-api/pkg/api"
	"github.com/kannan112/mock-trading-platform-api/pkg/api/handler"
	"github.com/kannan112/mock-trading-platform-api/pkg/api/middleware"
	"github.com/kannan112/mock-trading-platform-api/pkg/config"
	"github.com/kannan112/mock-trading-platform-api/pkg/db"
	"github.com/kannan112/mock-trading-platform-api/pkg/repository"
	"github.com/kannan112/mock-trading-platform-api/pkg/service/token"
	"github.com/kannan112/mock-trading-platform-api/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.ServerHTTP, error) {
	tokenService := token.NewTokenService(cfg)
	middlewareMiddleware := middleware.NewMiddleware(tokenService)
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository, tokenService)
	userHandler := handler.NewUserHandler(userUseCase, tokenService)
	serverHTTP := http.NewServerHTTP(middlewareMiddleware, userHandler)
	return serverHTTP, nil
}
